/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// Get Supabase URL and extract project ID
// Use optional chaining to prevent errors if import.meta.env is undefined
const supabaseUrl = import.meta.env?.VITE_SUPABASE_URL || 'https://faczbtutzsrcnlrahifb.supabase.co'
const anonKey = import.meta.env?.VITE_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhY3pidHV0enNyY25scmFoaWZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ0OTE3MTMsImV4cCI6MjA4MDA2NzcxM30.2PYn_okTcGJ78VtwEq6uN3ESKBmOb1r6bZALIV10lGc'

// Extract project ID from URL (e.g., https://PROJECT_ID.supabase.co)
export const projectId = supabaseUrl.split('//')[1]?.split('.')[0] || 'faczbtutzsrcnlrahifb'
export const publicAnonKey = anonKey